# Generated by Django 2.0.6 on 2019-09-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('realName', models.CharField(max_length=200)),
                ('accountNumber', models.DecimalField(decimal_places=0, max_digits=20)),
                ('balance', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='NewDog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('breed', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
            ],
        ),
    ]
